image: maven:3.9.8-eclipse-temurin-21-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - apk add --update openssh-client bash openssl rsync gettext tzdata unzip
  - eval $(ssh-agent -s)
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - echo $SSH_KEY | base64 -d | tr -d '\r' | ssh-add - > /dev/null
  - DEPLOY_SERVERS_ARRAY=(`echo $DEPLOY_SERVER | tr ',' ' '`)
  - for i in "${DEPLOY_SERVERS_ARRAY[@]}"; do ssh-keyscan $i >> ~/.ssh/known_hosts; chmod 600 ~/.ssh/*; done

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test

.deploy_script:
  stage: deploy
  script:
    # 1. Build ZIP without tests
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests

    # 2. Get version and zip file name
    - VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
    - ZIP_FILE=px-submission-tool-${VERSION}.zip
    - echo "Deploying $ZIP_FILE"

    # 3. Copy ZIP to login node temp location
    - scp target/$ZIP_FILE $SERVER_USER@$DEPLOY_SERVER:/tmp/$ZIP_FILE

    # 4. Use srun + become to deploy zip as $SUDO_USER (e.g. pride_adm)
    - ssh $SERVER_USER@$DEPLOY_SERVER "
      /ebi/slurm/codon/bin/srun --cpus-per-task 1 --mem-per-cpu 150 --time 6:00:00 -p datamover --export=ALL bash -c '
      become $SUDO_USER && \
      mkdir -p $DEPLOY_PATH/$VERSION && \
      mv /tmp/$ZIP_FILE $DEPLOY_PATH/$VERSION/ && \
      chmod -R 777 $DEPLOY_PATH/$VERSION
      '
      "

    # 5. Update symlink (also as $SUDO_USER) pointing to the latest versioned zip
    - ssh $SERVER_USER@$DEPLOY_SERVER "
      /ebi/slurm/codon/bin/srun --cpus-per-task 1 --mem-per-cpu 150 --time 6:00:00 -p datamover --export=ALL bash -c '
            become $SUDO_USER && \
            cd $SYMLINK_PATH && ln -snf $DEPLOY_PATH_RELATIVE_TO_SYMLINK/$VERSION/$ZIP_FILE $SYMLINK'
        "


deploy_prod:
  environment: prod
  extends: .deploy_script
  #  only:
  #    - master
  when: manual

deploy_dev:
  environment: dev
  extends: .deploy_script
  #  only:
  #    - master
  when: manual
